AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'db/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/UselessAssignment:
  Enabled: true
